### Reading Data from Different Sources

In [2]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "jamesh@gmail.com", "job_profile": [{"title1": "Team Lead", "title2": "Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [3]:
df

,employee_name,email,job_profile
0,James,jamesh@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [4]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"jamesh@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [6]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"jamesh@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [7]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"jamesh@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [9]:
df.to_csv("wine.csv")

In [11]:
!pip install lxml

Requirement already satisfied: lxml in d:\anaconda3\lib\site-packages (5.3.0)

In [10]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"

df=pd.read_html(url)

In [12]:
df

[                                            Bank Name                City  \
 0             Community Bank and Trust - West Georgia            LaGrange
 1                   Metropolitan Capital Bank & Trust             Chicago
 2                        The Santa Anna National Bank          Santa Anna
 3                                Pulaski Savings Bank             Chicago
 4                  The First National Bank of Lindsay             Lindsay
 5               Republic First Bank dba Republic Bank        Philadelphia
 6                                       Citizens Bank            Sac City
 7                            Heartland Tri-State Bank             Elkhart
 8                                 First Republic Bank       San Francisco
 9                                      Signature Bank            New York
 10                                Silicon Valley Bank         Santa Clara
 11                                  Almena State Bank              Almena
 12                         First City Bank of Florida   Fort Walton Beach
 13                               The First State Bank       Barboursville
 14                                 Ericson State Bank             Ericson
 15                   City National Bank of New Jersey              Newark
 16                                      Resolute Bank              Maumee
 17                              Louisa Community Bank              Louisa
 18                               The Enloe State Bank              Cooper
 19                Washington Federal Bank for Savings             Chicago
 20    The Farmers and Merchants State Bank of Argonia             Argonia
 21                                Fayette County Bank          Saint Elmo
 22  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 23                                     First NBC Bank         New Orleans
 24                                      Proficio Bank  Cottonwood Heights

             State   Cert                Acquiring Institution  \
 0         Georgia  25796                          Anchor Bank
 1        Illinois  57488              First Independence Bank
 2           Texas   5520            Coleman County State Bank
 3        Illinois  28611                      Millennium Bank
 4        Oklahoma   4134               First Bank & Trust Co.
 5    Pennsylvania  27332    Fulton Bank, National Association
 6            Iowa   8758            Iowa Trust & Savings Bank
 7          Kansas  25851               Dream First Bank, N.A.
 8      California  59017            JPMorgan Chase Bank, N.A.
 9        New York  57053                  Flagstar Bank, N.A.
 10     California  24735  First–Citizens Bank & Trust Company
 11         Kansas  15426                          Equity Bank
 12        Florida  16748            United Fidelity Bank, fsb
 13  West Virginia  14361                       MVB Bank, Inc.
 14       Nebraska  18265           Farmers and Merchants Bank
 15     New Jersey  21111                      Industrial Bank
 16           Ohio  58317                   Buckeye State Bank
 17       Kentucky  58112    Kentucky Farmers Bank Corporation
 18          Texas  10716                   Legend Bank, N. A.
 19       Illinois  30570                   Royal Savings Bank
 20         Kansas  17719                          Conway Bank
 21       Illinois   1802            United Fidelity Bank, fsb
 22      Wisconsin  30003  First-Citizens Bank & Trust Company
 23      Louisiana  58302                         Whitney Bank
 24           Utah  35495                    Cache Valley Bank

          Closing Date  Fund  Sort ascending
 0         May 1, 2026                 10551
 1    January 30, 2026                 10550
 2       June 27, 2025                 10549
 3    January 17, 2025                 10548
 4    October 18, 2024                 10547
 5      April 26, 2024                 10546
 6    November 3, 2023                 10545
 7       July 28, 2023                 10544
 8         May 1, 2023                 10543
 9      March 12, 2023                 10540
 10     March 10, 2023                 10539
 11   October 23, 2020                 10538
 12   October 16, 2020                 10537
 13      April 3, 2020                 10536
 14  February 14, 2020                 10535
 15   November 1, 2019                 10534
 16   October 25, 2019                 10533
 17   October 25, 2019                 10532
 18       May 31, 2019                 10531
 19  December 15, 2017                 10530
 20   October 13, 2017                 10529
 21       May 26, 2017                 10528
 22        May 5, 2017                 10527
 23     April 28, 2017                 10526
 24      March 3, 2017                 10525  ]

In [22]:
df_excel=pd.read_excel('data.xlsx')

In [23]:
df_excel.to_pickle('df_excel')

In [24]:
pd.read_pickle('df_excel')

   Name  Age
0  Sonu   21
1  Jack   34
2  John   32