## Label Encoding

In [6]:
import pandas as pd
df = pd.DataFrame({
    'color': ['red','blue', 'green', 'green', 'red', 'blue']
})
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [7]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [8]:
lbl_encoder.fit_transform(df[['color']])

d:\Anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [9]:
lbl_encoder.transform([['red']])

d:\Anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [10]:
lbl_encoder.transform([['blue']])

d:\Anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

## Ordinal Encoding

In [11]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df = pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

In [13]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [14]:
## Create an instances of ordinal Encoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [15]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [16]:
encoder.transform([['small']])

d:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])